// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dolxahuhpjlqocogctca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvbHhhaHVocGpscW9jb2djdGNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDM4NjksImV4cCI6MjA2NTU3OTg2OX0.gr-_7L8eraFFPQ7UDHyPpoSyLa1pVQyoUrUYQ6gfwvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});